### ISSUE TITLE
Add a `pyproject.toml`

### ISSUE THREAD

**Issue by timokau** [kiudee/cs-ranking#110]
The current standards for specifying the build of a python project, its dependencies and the configuration of various tools is [pyproject.toml](https://www.python.org/dev/peps/pep-0518/). It may be a good idea to adopt this. There are [some](https://github.com/python/mypy/issues/5205) [holdouts](https://gitlab.com/pycqa/flake8/issues/428) for the tools. Specifying the build system without needing to run a python program (which may have dependencies itself) is the biggest benefit.

**Comment by kiudee** [comment]
That is a good idea. In my new projects I migrated to a pyproject.toml in conjunction with the usage of [poetry](https://python-poetry.org/).
