### ISSUE TITLE
Check if dataset generator exists and otherwise raise an exception

### ISSUE THREAD

**Issue by kiudee** [kiudee/cs-ranking#122]
Currently, if the dataset generator receives an invalid dataset, it silently picks a default generator.
https://github.com/kiudee/cs-ranking/blob/5bdc0e414dde196761b7c827369b605a024bae42/csrank/dataset_reader/objectranking/object_ranking_data_generator.py#L35-L36
This is unexpected behavior and should be changed. If the dataset generator is unknown, an exception should be raised.

We should check all dataset generators/parsers for similar behavior.

**Comment by prithagupta** [comment]
Its ok @timokau
