### ISSUE TITLE
FATE Choice ignores parameters of the fit method

### ISSUE THREAD

**Issue by helegraf** [kiudee/cs-ranking#126]
The fit method parameters are:

https://github.com/kiudee/cs-ranking/blob/49e39df3257679acb157b4ca0f47a8bfaa73866a/csrank/choicefunction/fate_choice.py#L134-L150

However the parameters are not passed to the super class:

https://github.com/kiudee/cs-ranking/blob/49e39df3257679acb157b4ca0f47a8bfaa73866a/csrank/choicefunction/fate_choice.py#L199

https://github.com/kiudee/cs-ranking/blob/49e39df3257679acb157b4ca0f47a8bfaa73866a/csrank/choicefunction/fate_choice.py#L208

**Comment by kiudee** [comment]
Good find, that is indeed bad and would warrant a bug fix release.

**Comment by timokau** [comment]
Thanks for reporting :)
