### ISSUE TITLE
Release 1.2

### ISSUE THREAD

**Issue by timokau** [kiudee/cs-ranking#135]
Since the last release, we have [improved the UX of our API](https://github.com/kiudee/cs-ranking/pull/118), [fixed unexpected](https://github.com/kiudee/cs-ranking/pull/123) [behaviour](https://github.com/kiudee/cs-ranking/pull/123), fixed [a few](https://github.com/kiudee/cs-ranking/pull/134) [bugs](https://github.com/kiudee/cs-ranking/pull/129) and did some [refactoring](https://github.com/kiudee/cs-ranking/pull/117). That's just off the top of my head, there are probably other things as well.

We should think about a new release.

**Comment by kiudee** [comment]
I think after merging #134, we can create v1.2.0. I adjusted the milestone accordingly.
