### ISSUE TITLE
ChoiceDatasetGenerator can not be instantiated

### ISSUE THREAD

**Issue by kiudee** [kiudee/cs-ranking#166]
Trying to instantiate the ChoiceDatasetGenerator as described in our [tutorial](https://cs-ranking.readthedocs.io/en/latest/notebooks/Rank-Net-Choice.html):
```python
from csrank import ChoiceDatasetGenerator
seed = 12
n_train = 10000
n_test = 10000
n_features = 2
n_objects = 40
gen = ChoiceDatasetGenerator(dataset_type='pareto', random_state=seed,
                                n_train_instances=n_train,
                                n_test_instances=n_test,
                                n_objects=n_objects,
                                n_features=n_features)
```
fails with the error:
```
TypeError: Can't instantiate abstract class ChoiceDatasetGenerator with abstract methods get_train_test_datasets
```

**Comment by timokau** [comment]
`get_train_test_datasets` is marked as abstract in `DatasetReader` and is not overriden in `ChoiceDatasetGenerator` (or its superclass `SyntheticDatasetGenerator`).

`DatasetReader` does provide a default implementaiton for it though, based on the `splitter` function which *is* implemented in `SyntheticDatasetGenerator`. So it should be sufficient to just remove the `abstractmethod` marker for `get_train_test_datasets`.

**Comment by timokau** [comment]
Done in https://github.com/kiudee/cs-ranking/pull/167.
