### ISSUE TITLE
Fix test for the FATE ranker

### ISSUE THREAD

**Issue by kiudee** [kiudee/cs-ranking#27]
It appears from the failed build 158 that the test https://github.com/kiudee/cs-ranking/blob/bb143bccf5e422ce6fb42af89a98f2137affce66/csrank/tests/test_ranking.py#L75
can fail with some probability because the training is random.

We should ensure, that it only fails if the underlying model is broken.

**Comment by prithagupta** [comment]
I think if we initialize tensor flow and keras with a seed then it's deterministic

**Comment by prithagupta** [comment]
I think if we initialize tensor flow and keras with a seed then it's deterministic
