### ISSUE TITLE
Implement Tests

### ISSUE THREAD

**Issue by prithagupta** [kiudee/cs-ranking#43]
- [x] Learners
	- [x] Object Ranking
	- [x] Discrete Choice
	- [x] General Choice Functions
- [ ] Dataset Parsers
- [x] Metrics
- [x] Losses

**Comment by kiudee** [comment]
The current goal is to make the library compliant with sklearn interfaces, which would allow the user to use any compatible hyperparameter tuner.
Thus I would say we can cross off hyperparameter optimization here.
