### ISSUE TITLE
Speed up Travis-CI builds

### ISSUE THREAD

**Issue by kiudee** [kiudee/cs-ranking#51]
Currently, the tests for the probabilistic models implemented in PyMC3 take a long time to run, which causes a long delay between updating a pull request and receiving Travis confirmation.

Measures
--------
 - [x] Parallelize build using several environments
 - [x] Speed up PyMC3 tests
 - [ ] Speed up installation process and optimize caching (if possible)

**Comment by prithagupta** [comment]
Currently, the tests are optimized for pymc3 models. The problem is the test pipeline in which the installation is done everytime.

**Comment by kiudee** [comment]
One additional way to speed up builds is to parallelize them Travis CI’s build matrix feature:
https://docs.travis-ci.com/user/speeding-up-the-build/

**Comment by timokau** [comment]
Is this still relevant, or are we satisfied with the build matrix parallelization? If it is still relevant, should this really belong to the 1.1 milestone?

**Comment by kiudee** [comment]
I think for now we can close this issue.
