### ISSUE TITLE
Move scripts for the experiments to another repository

### ISSUE THREAD

**Issue by kiudee** [kiudee/cs-ranking#60]
Currently, the scripts we use for our experiments are still part of this repository. Since this repository is moving towards being a library for object ranking and choice, this code should be moved to a separate repository.

**Comment by timokau** [comment]
@prithagupta, if I recall correctly you once said that we could just remove the scripts since they will still be available in the commit history. Is that right?

**Comment by prithagupta** [comment]
Yes, you can remove them, I have made a branch bug_fixes, which has the code for the current experiments.
