### ISSUE TITLE
Sequence-based indexing in theano is deprecated

### ISSUE THREAD

**Issue by timokau** [kiudee/cs-ranking#74]
In `csrank/discretechoice/nested_logit_model.py` we make use of sequence indexing in theano multiple times. For example:

https://github.com/kiudee/cs-ranking/blob/ba03234fb61a4e645b393d2d9ac81c0b85399024/csrank/discretechoice/nested_logit_model.py#L175

Here `rows` and `cols` are both 1d tensors which are then used to index a different tensor:

https://github.com/kiudee/cs-ranking/blob/ba03234fb61a4e645b393d2d9ac81c0b85399024/csrank/discretechoice/nested_logit_model.py#L176

Theano complains that this is deprecated:

```
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
```

I'm not sure how to fix this. According to the [documentation](http://deeplearning.net/software/theano/library/tensor/basic.html), theano should support boolean mask indexing. So I thought we should be able to do

```
mask = tt.eq(self.y_nests, i)
utility = tt.set_subtensor(utility[mask], tt.dot(self.Xt[mask], weights[i]))
```

instead (as `tt.eq` should return a boolean mask). But unfortunately that doesn't work; it gives the same warning.

Any ideas?

**Comment by kiudee** [comment]
I think this problem was caused by a new version of NumPy and has been discussed here:
https://github.com/Theano/Theano/pull/6703

**Comment by timokau** [comment]
Right, so the api is still supported by theano. I've confirmed that the issue is fixed in upstream by running the testsuite with a patched theano. Another case of "not our fault" then.

**Comment by timokau** [comment]
For us, the commits 082yqypw8vddxly47p26l9sgda3z598i098dldp2d0k04vawlblx and 0y2g08arbcffgkd9w0aan1g2yn7n06ma8qwd8i2vvbj5z1n28xvq are interesting (not included in the PR you linked, but similar in intention).
