### ISSUE TITLE
Document the release process

### ISSUE THREAD

**Issue by kiudee** [kiudee/cs-ranking#89]
We are using `bump2version` now to change the version number and create a tagged commit. This triggers an upload of the new version to PyPi.
At the same time the `HISTORY.rst` file needs to be updated with the recent changes.

This process should be documented in Sphinx.

The correct order is:

1. Update `HISTORY.rst` and commit.
2. Run `bump2version [patch|minor|major]`
3. Push commits and tag to master/branch.

**Comment by timokau** [comment]
Will be included in https://github.com/kiudee/cs-ranking/pull/91.
